robot_description : 'robot_description'
base_link : 'base_link'
floor_to_base_height : -0.9

#default grasp params
joints : ['hand_right_index_joint', 'hand_right_middle_joint', 'hand_right_thumb_joint']
pregrasp_posture : [0.0, 0.0, 2.0]
pregrasp_time_from_start : 4.0
grasp_posture : [4.5, 4.5, 2.0]
grasp_time_from_start : 4.0

#desired pose from end effector to grasp
grasp_pose_to_eef : [0.054, 0.0, 0.018]

end_effector_name: 'right_hand'
end_effector_parent_link: 'right_hand_grasping_frame'

