base_link: '/odom'

# =====================================================
left_hand:
    end_effector_name: 'left_hand'  #ee group name

    #actuated joints in end effector
    joints : ['LHand']

    #open position
    pregrasp_posture : [0.0] #for sim
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [1.0] #for sim
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    #desired pose from end effector to grasp - [r, p, y] #1.5707 = PI/2
    #side grasp -65deg
    grasp_pose_to_eef : [-0.09, 0.036, -0.02]
    grasp_pose_to_eef_rotation : [-1.22, 0.0, 0.0]

    end_effector_parent_link: 'l_wrist'
# =====================================================
right_hand:
    end_effector_name: 'right_hand'  #ee group name

    #actuated joints in end effector
    joints : ['RHand']

    #open position
    pregrasp_posture : [0.0] #for sim
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [1.0] #for sim
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    #desired pose from end effector to grasp - [r, p, y]
    #side grasp 65deg
    grasp_pose_to_eef : [-0.09, -0.036, -0.02]
    grasp_pose_to_eef_rotation : [1.22, 0.0, 0.0]

    end_effector_parent_link: 'r_wrist'

